{
 "title": "Builds",
 "tags": [
  "Liferay",
  "Builds"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "build_id",
    "label": "Build ID",
    "query": {
     "query": "query_result(count by (build_id) (max_over_time(logging_googleapis_com:user_cloudbuild_build_lifecycle_total[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 }, "options": { "content": "${BUILDS_HTML}" } },
  {
   "title": "SUCCESS RUNS #",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(\r\n  sum by (build_id) (\r\n    max_over_time(logging_googleapis_com:user_cloudbuild_build_lifecycle_total{status=\"DONE\"}[$__range])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FAILED RUNS #",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(\r\n  sum by (build_id) (\r\n    max_over_time(logging_googleapis_com:user_cloudbuild_build_lifecycle_total{status=~\"ERROR|FAILURE|TIMEOUT|CANCELLED\"}[$__range])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL RUNS #",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(\r\n  sum by (build_id) (\r\n    last_over_time(logging_googleapis_com:user_cloudbuild_build_lifecycle_total{status!=\"starting\"}[$__range])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Builds",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (build_id, build_trigger_id) (min_over_time(timestamp({\"__name__\"=\"logging.googleapis.com/user/cloudbuild-build-lifecycle-total\", \"status\"=\"starting\"})[$__range:])) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (build_id, status) (min_over_time(timestamp({\"__name__\"=\"logging.googleapis.com/user/cloudbuild-build-lifecycle-total\", \"status\"!=\"starting\"})[$__range:])) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (build_id, git_commit_url) (last_over_time({\"__name__\"=\"logging.googleapis.com/user/cloudbuild-commit-metadata-total\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Failure Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  sum by (build_id) (\r\n    max_over_time(logging_googleapis_com:user_cloudbuild_build_lifecycle_total{status=~\"ERROR|FAILURE|TIMEOUT|CANCELLED\"}[$__range])\r\n  )\r\n)\r\n/\r\ncount(\r\n  sum by (build_id) (\r\n    max_over_time(logging_googleapis_com:user_cloudbuild_build_lifecycle_total{status!=\"starting\"}[$__range])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Steps - Build ID: $build_id",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (step_number, step_name) (min_over_time(timestamp({\"__name__\"=\"logging.googleapis.com/user/cloudbuild-step-lifecycle-total\", \"build_id\"=\"$build_id\", status=\"Starting\"})[$__range:])) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (step_number, status) (min_over_time(timestamp({\"__name__\"=\"logging.googleapis.com/user/cloudbuild-step-lifecycle-total\", \"build_id\"=\"$build_id\", status!=\"Starting\"})[$__range:])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs - Build ID: $build_id",
   "type": "logs",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 13 },
   "targets": [
    {
     "bucketId": "us-west1/buckets/workspace",
     "projectId": "liferaycloud-dev-cust-d1",
     "queryText": "severity >= DEFAULT\nresource.type = \"build\"\nresource.labels.build_id = \"$build_id\"",
     "viewId": "_AllLogs"
    }
   ]
  }
 ]
}