{{- if .Values.smtp.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    labels:
        {{- include "observability-paas.labels" . | nindent 8 }}
    name: {{ .Values.smtp.externalSecret.name | quote }}
    namespace: {{ include "observability-paas.namespace" . | quote }}
spec:
    dataFrom:
        -   extract:
                conversionStrategy: Default
                decodingStrategy: None
                key: {{ required "smtp.externalSecret.remoteSecretName is required when smtp.enabled is true" .Values.smtp.externalSecret.remoteSecretName | quote }}
                metadataPolicy: None
                nullBytePolicy: Ignore
    refreshInterval: 1h0m0s
    secretStoreRef:
        kind: ClusterSecretStore
        name: {{ default "gcpsm-css" .Values.smtp.externalSecret.secretStoreName | quote }}
{{- end }}